<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>ManifoldSolver.Core</AssemblyName>
    <RootNamespace>ManifoldSolver.Core</RootNamespace>
	  <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="View\RunnerPage.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CADBooster.SolidDna" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="View\RunnerPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </Page>
  </ItemGroup>
</Project>